name: Laravel Testing

on:
  push:
    # branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  laravel-testing:
    runs-on: ubuntu-latest

    services:
      db:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: oseru-survey_test
          MYSQL_USER: newone
          MYSQL_PASSWORD: oseru_test
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3
      mailhog:
        image: mailhog/mailhog
        ports:
          - 1025:1025
          - 8025:8025

    steps:
    - uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.1'
        extensions: zip, mysql

    - name: Install Composer dependencies
      run: composer install --no-interaction --prefer-dist

    - name: Generate .env.testing File
      run: |
        echo "APP_KEY=base64:$(php -r 'echo base64_encode(random_bytes(32));')" > .env.testing
        echo "DB_CONNECTION=mysql" >> .env.testing
        echo "DB_HOST=127.0.0.1" >> .env.testing
        echo "DB_PORT=3306" >> .env.testing
        echo "DB_DATABASE=oseru-survey_test" >> .env.testing
        echo "DB_USERNAME=newone" >> .env.testing
        echo "DB_PASSWORD=test" >> .env.testing
        echo "MAIL_MAILER=smtp" >> .env.testing
        echo "MAIL_HOST=127.0.0.1" >> .env.testing
        echo "MAIL_PORT=1025" >> .env.testing
        echo "MAIL_USERNAME=null" >> .env.testing
        echo "MAIL_PASSWORD=null" >> .env.testing
        echo "MAIL_ENCRYPTION=null" >> .env.testing

    - name: Laravel Migrate
      env:
        APP_ENV: testing
        DB_CONNECTION: mysql
        DB_HOST: 127.0.0.1
        DB_PORT: 3306
        DB_DATABASE: oseru-survey_test
        DB_USERNAME: newone
        DB_PASSWORD: oseru_test
      run: php artisan migrate --force

    - name: Run Tests
      env:
        APP_ENV: testing
        DB_CONNECTION: mysql
        DB_HOST: 127.0.0.1
        DB_PORT: 3306
        DB_DATABASE: oseru-survey_test
        DB_USERNAME: newone
        DB_PASSWORD: oseru_test
      run: php artisan test
